version: "3.8"

services:
  api-gateway:
    build:
      context: .
      target: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - product-microservice
      - auth-microservice
    volumes:
      - ./apps/backend/api-gateway:/prod/api-gateway
      - /prod/api-gateway/node_modules
    environment:
      - PRODUCT_MICROSERVICE_URL=http://product-microservice:8001
      - PORT=8000
      - FRONTEND_URL=http://localhost:3000
      - AUTH_MICROSERVICE_URL=http://auth-microservice:8002
  product-microservice:
    build:
      context: .
      target: product-microservice
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@product_db:5432/products
      - PORT=8001
      - API_GATEWAY_URL=http://api-gateway:8000
    volumes:
      - ./apps/backend/product-microservice:/prod/product-microservice
      - /prod/product-microservice/node_modules
    depends_on:
      - product_db
  auth-microservice:
    build:
      context: .
      target: auth-microservice
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@auth_db:5432/auth
      - PORT=8002
      - API_GATEWAY_URL=http://api-gateway:8000
    volumes:
      - ./apps/backend/auth-microservice:/prod/auth-microservice
      - /prod/auth-microservice/node_modules
    depends_on:
      - auth_db
  product_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
  auth_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5435:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

volumes:
  product_data:
  auth_data: