apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: backend-api-gateway
    context: ./api-gateway
    docker:
      dockerfile: docker/k8s/dev/Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
      - src: 'package.json'
        dest: .
      - src: 'package-lock.json'
        dest: .
  - image: backend-product-microservice
    context: ./product-microservice
    docker:
      dockerfile: docker/k8s/dev/Dockerfile
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .
      - src: 'package.json'
        dest: .
      - src: 'package-lock.json'
        dest: .
      - src: 'generated/**'
        dest: .
manifests:
  kustomize:
    paths:
    - k8s/overlays/dev
portForward:
- resourceType: service
  resourceName: api-gateway-service
  namespace: dev-backend
  port: 80
  localPort: 8000
- resourceType: service
  resourceName: product-microservice-service
  namespace: dev-backend
  port: 8001
  localPort: 8001
- resourceType: service
  resourceName: product-microservice-service
  namespace: dev-backend
  port: 50051
  localPort: 50051
