// source: AuthCommunication.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require("google-protobuf");
var goog = jspb;
var global = function () {
  if (this) {
    return this;
  }
  if (typeof window !== "undefined") {
    return window;
  }
  if (typeof global !== "undefined") {
    return global;
  }
  if (typeof self !== "undefined") {
    return self;
  }
  return Function("return this")();
}.call(null);

goog.exportSymbol(
  "proto.productcommunication.CreateProfileRequest",
  null,
  global,
);
goog.exportSymbol(
  "proto.productcommunication.CreateProfileResponse",
  null,
  global,
);
goog.exportSymbol("proto.productcommunication.Role", null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.productcommunication.CreateProfileRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.productcommunication.CreateProfileRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.productcommunication.CreateProfileRequest.displayName =
    "proto.productcommunication.CreateProfileRequest";
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.productcommunication.CreateProfileResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.productcommunication.CreateProfileResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.productcommunication.CreateProfileResponse.displayName =
    "proto.productcommunication.CreateProfileResponse";
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.productcommunication.CreateProfileRequest.prototype.toObject =
    function (opt_includeInstance) {
      return proto.productcommunication.CreateProfileRequest.toObject(
        opt_includeInstance,
        this,
      );
    };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.productcommunication.CreateProfileRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.productcommunication.CreateProfileRequest.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, ""),
        name: jspb.Message.getFieldWithDefault(msg, 2, ""),
        surname: jspb.Message.getFieldWithDefault(msg, 3, ""),
        role: jspb.Message.getFieldWithDefault(msg, 4, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.productcommunication.CreateProfileRequest}
 */
proto.productcommunication.CreateProfileRequest.deserializeBinary = function (
  bytes,
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.productcommunication.CreateProfileRequest();
  return proto.productcommunication.CreateProfileRequest.deserializeBinaryFromReader(
    msg,
    reader,
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.productcommunication.CreateProfileRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.productcommunication.CreateProfileRequest}
 */
proto.productcommunication.CreateProfileRequest.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {string} */ (reader.readString());
          msg.setId(value);
          break;
        case 2:
          var value = /** @type {string} */ (reader.readString());
          msg.setName(value);
          break;
        case 3:
          var value = /** @type {string} */ (reader.readString());
          msg.setSurname(value);
          break;
        case 4:
          var value = /** @type {!proto.productcommunication.Role} */ (
            reader.readEnum()
          );
          msg.setRole(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.productcommunication.CreateProfileRequest.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.productcommunication.CreateProfileRequest.serializeBinaryToWriter(
      this,
      writer,
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.productcommunication.CreateProfileRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.productcommunication.CreateProfileRequest.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined;
    f = message.getId();
    if (f.length > 0) {
      writer.writeString(1, f);
    }
    f = message.getName();
    if (f.length > 0) {
      writer.writeString(2, f);
    }
    f = message.getSurname();
    if (f.length > 0) {
      writer.writeString(3, f);
    }
    f = message.getRole();
    if (f !== 0.0) {
      writer.writeEnum(4, f);
    }
  };

/**
 * optional string id = 1;
 * @return {string}
 */
proto.productcommunication.CreateProfileRequest.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};

/**
 * @param {string} value
 * @return {!proto.productcommunication.CreateProfileRequest} returns this
 */
proto.productcommunication.CreateProfileRequest.prototype.setId = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string name = 2;
 * @return {string}
 */
proto.productcommunication.CreateProfileRequest.prototype.getName =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 2, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.productcommunication.CreateProfileRequest} returns this
 */
proto.productcommunication.CreateProfileRequest.prototype.setName = function (
  value,
) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string surname = 3;
 * @return {string}
 */
proto.productcommunication.CreateProfileRequest.prototype.getSurname =
  function () {
    return /** @type {string} */ (
      jspb.Message.getFieldWithDefault(this, 3, "")
    );
  };

/**
 * @param {string} value
 * @return {!proto.productcommunication.CreateProfileRequest} returns this
 */
proto.productcommunication.CreateProfileRequest.prototype.setSurname =
  function (value) {
    return jspb.Message.setProto3StringField(this, 3, value);
  };

/**
 * optional Role role = 4;
 * @return {!proto.productcommunication.Role}
 */
proto.productcommunication.CreateProfileRequest.prototype.getRole =
  function () {
    return /** @type {!proto.productcommunication.Role} */ (
      jspb.Message.getFieldWithDefault(this, 4, 0)
    );
  };

/**
 * @param {!proto.productcommunication.Role} value
 * @return {!proto.productcommunication.CreateProfileRequest} returns this
 */
proto.productcommunication.CreateProfileRequest.prototype.setRole = function (
  value,
) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.productcommunication.CreateProfileResponse.prototype.toObject =
    function (opt_includeInstance) {
      return proto.productcommunication.CreateProfileResponse.toObject(
        opt_includeInstance,
        this,
      );
    };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.productcommunication.CreateProfileResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.productcommunication.CreateProfileResponse.toObject = function (
    includeInstance,
    msg,
  ) {
    var f,
      obj = {
        isValid: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.productcommunication.CreateProfileResponse}
 */
proto.productcommunication.CreateProfileResponse.deserializeBinary = function (
  bytes,
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.productcommunication.CreateProfileResponse();
  return proto.productcommunication.CreateProfileResponse.deserializeBinaryFromReader(
    msg,
    reader,
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.productcommunication.CreateProfileResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.productcommunication.CreateProfileResponse}
 */
proto.productcommunication.CreateProfileResponse.deserializeBinaryFromReader =
  function (msg, reader) {
    while (reader.nextField()) {
      if (reader.isEndGroup()) {
        break;
      }
      var field = reader.getFieldNumber();
      switch (field) {
        case 1:
          var value = /** @type {boolean} */ (reader.readBool());
          msg.setIsValid(value);
          break;
        default:
          reader.skipField();
          break;
      }
    }
    return msg;
  };

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.productcommunication.CreateProfileResponse.prototype.serializeBinary =
  function () {
    var writer = new jspb.BinaryWriter();
    proto.productcommunication.CreateProfileResponse.serializeBinaryToWriter(
      this,
      writer,
    );
    return writer.getResultBuffer();
  };

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.productcommunication.CreateProfileResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.productcommunication.CreateProfileResponse.serializeBinaryToWriter =
  function (message, writer) {
    var f = undefined;
    f = message.getIsValid();
    if (f) {
      writer.writeBool(1, f);
    }
  };

/**
 * optional bool is_valid = 1;
 * @return {boolean}
 */
proto.productcommunication.CreateProfileResponse.prototype.getIsValid =
  function () {
    return /** @type {boolean} */ (
      jspb.Message.getBooleanFieldWithDefault(this, 1, false)
    );
  };

/**
 * @param {boolean} value
 * @return {!proto.productcommunication.CreateProfileResponse} returns this
 */
proto.productcommunication.CreateProfileResponse.prototype.setIsValid =
  function (value) {
    return jspb.Message.setProto3BooleanField(this, 1, value);
  };

/**
 * @enum {number}
 */
proto.productcommunication.Role = {
  INSTRUCTOR: 0,
  COORDINATOR: 1,
  STUDENT: 2,
};

goog.object.extend(exports, proto.productcommunication);
